let cards = [
    {    "manaCost": "{3}{W}",    "multiverseid": 452755,    "colors": [      "White"    ],    "cmc": 4  },
    {    "manaCost": "{3}{W}",    "multiverseid": 452757,    "colors": [      "White"    ],    "cmc": 4  },
    {    "manaCost": "{W}",    "multiverseid": 452773,    "colors": [      "White"    ],    "cmc": 1  },
    {    "manaCost": "{W}",    "multiverseid": 452778,    "colors": [      "White"    ],    "cmc": 1  },
    {    "manaCost": "{3}{U}",    "multiverseid": 452781,    "colors": [      "Blue"    ],    "cmc": 4  },
    {    "manaCost": "{3}{U}",    "multiverseid": 452782,    "colors": [      "Blue"    ],    "cmc": 4  },
    {    "manaCost": "{U}",    "multiverseid": 452784,    "colors": [      "Blue"    ],    "cmc": 1  },
    {    "manaCost": "{2}{U}{U}",    "multiverseid": 452785,    "colors": [      "Blue"    ],    "cmc": 4  },
    {    "manaCost": "{1}{U}",    "multiverseid": 452787,    "colors": [      "Blue"    ],    "cmc": 2  },
    {    "manaCost": "{4}{U}{U}",    "multiverseid": 452788,    "colors": [      "Blue"    ],    "cmc": 6  },
    {    "manaCost": "{U}{U}",    "multiverseid": 452794,    "colors": [      "Blue"    ],    "cmc": 2  },
    {    "manaCost": "{1}{U}",    "multiverseid": 452802,    "colors": [      "Blue"    ],    "cmc": 2  },
    {    "manaCost": "{1}{U}{U}",    "multiverseid": 452804,    "colors": [      "Blue"    ],    "cmc": 3  },
    {    "manaCost": "{1}{U}",    "multiverseid": 452806,    "colors": [      "Blue"    ],    "cmc": 2  },
    {    "manaCost": "{1}{B}",    "multiverseid": 452825,    "colors": [      "Black"    ],    "cmc": 2  },
    {    "manaCost": "{B}",    "multiverseid": 452829,    "colors": [      "Black"    ],    "cmc": 1  },
    {    "manaCost": "{3}{B}",    "multiverseid": 452833,    "colors": [      "Black"    ],    "cmc": 4  },
    {    "manaCost": "{4}{R}",    "multiverseid": 452844,    "colors": [      "Red"    ],    "cmc": 5  },
    {    "manaCost": "{4}{R}{R}",    "multiverseid": 452857,    "colors": [      "Red"    ],    "cmc": 6  },
    {    "manaCost": "{2}{R}",    "multiverseid": 452863,    "colors": [      "Red"    ],    "cmc": 3  },
    {    "manaCost": "{1}{R}",    "multiverseid": 452868,    "colors": [      "Red"    ],    "cmc": 2  },
    {    "manaCost": "{4}{G}{G}",    "multiverseid": 452874,    "colors": [      "Green"    ],    "cmc": 6  },
    {    "manaCost": "{2}{G}",    "multiverseid": 452876,    "colors": [      "Green"    ],    "cmc": 3  },
    {    "manaCost": "{G}",    "multiverseid": 452887,    "colors": [      "Green"    ],    "cmc": 1  },
    {    "manaCost": "{2}{G}",    "multiverseid": 452889,    "colors": [      "Green"    ],    "cmc": 3  },
    {    "manaCost": "{2}{G}",    "multiverseid": 452890,    "colors": [      "Green"    ],    "cmc": 3  },
    {    "manaCost": "{2}{U}{B}",    "multiverseid": 452901,    "colors": [      "Blue",      "Black"    ],    "cmc": 4  },
    {    "manaCost": "{B}{G}",    "multiverseid": 452902,    "colors": [      "Black",      "Green"    ],    "cmc": 2  },
    {    "manaCost": "{1}{R}{W}",    "multiverseid": 452909,    "colors": [      "White",      "Red"    ],    "cmc": 3  },
    {    "manaCost": "{3}{U}{R}",    "multiverseid": 452928,    "colors": [      "Blue",      "Red"    ],    "cmc": 5  },
    {    "manaCost": "{1}{U}{R}",    "multiverseid": 452929,    "colors": [      "Blue",      "Red"    ],    "cmc": 3  },
    {    "manaCost": "{3}{G}{W}",    "multiverseid": 452931,    "colors": [      "White",      "Green"    ],    "cmc": 5  },
    {    "manaCost": "{R}{W}",    "multiverseid": 452932,    "colors": [      "White",      "Red"    ],    "cmc": 2  },
    {    "manaCost": "{X}{G}{W}{W}",    "multiverseid": 452938,    "colors": [      "White",      "Green"    ],    "cmc": 3  },
    {    "manaCost": "{1}{U}{R}",    "multiverseid": 452949,    "colors": [      "Blue",      "Red"    ],    "cmc": 3  },
    {    "manaCost": "{1}{U/B}{U/B}",    "multiverseid": 452970,    "colors": [      "Blue",      "Black"    ],    "cmc": 3  },
    {    "manaCost": "{G/W}{G/W}",    "multiverseid": 452971,    "colors": [      "White",      "Green"    ],    "cmc": 2  },
    {    "manaCost": "{4}{G}{W}",    "multiverseid": 452971,    "colors": [      "White",      "Green"    ],    "cmc": 6  },
    {    "manaCost": "{3}{U}{B}",    "multiverseid": 452973,    "colors": [      "Blue",      "Black"    ],    "cmc": 5  },
    {    "manaCost": "{U/R}{U/R}",    "multiverseid": 452974,    "colors": [      "Blue",      "Red"    ],    "cmc": 2  },
    {    "manaCost": "{X}{U}{U}{R}{R}",    "multiverseid": 452974,    "colors": [      "Blue",      "Red"    ],    "cmc": 4  },
    {    "manaCost": "{R/W}",    "multiverseid": 452977,    "colors": [      "White",      "Red"    ],    "cmc": 1  },
    {    "manaCost": "{2}{R}{W}",    "multiverseid": 452977,    "colors": [      "White",      "Red"    ],    "cmc": 4  },
    {    "manaCost": "{U/R}",    "multiverseid": 452978,    "colors": [      "Blue",      "Red"    ],    "cmc": 1  },
    {    "manaCost": "{4}{U}{R}",    "multiverseid": 452978,    "colors": [      "Blue",      "Red"    ],    "cmc": 6  },
    {    "manaCost": "{R/W}{R/W}",    "multiverseid": 452979,    "colors": [      "White",      "Red"    ],    "cmc": 2  },
    {    "manaCost": "{B/G}",    "multiverseid": 452980,    "colors": [      "Black",      "Green"    ],    "cmc": 1  },
    {    "manaCost": "{2}{B}{G}",    "multiverseid": 452980,    "colors": [      "Black",      "Green"    ],    "cmc": 4  }
]

